# device: NRF9151_XXCA
device: nRF54L15_M33
console_file: "test.log"
mcp: true
substitutions:
  RTC_SET: "rtc set {{UTC_NOW}}"
  LORA_KEY:
    shell: "openssl rand -hex 16 | tr a-z A-Z"
  GIT_SHA:
    shell: "git rev-parse --short HEAD"
    multiline: true
  CONFIG: |
    app config interval-sample 60
    app config interval-aggreg 300
    app config interval-report 1800
    {{RTC_SET}}
